### ISSUE TITLE
Interface Dose not Work

### ISSUE THREAD

**Issue by axiades** [svenseeberg/mailadmin#13]
[Thu Jan 31 00:15:59.901447 2019] [php7:notice] [pid 2206] [client 31.16.189.122:60868] PHP Notice:  Undefined index: path in /var/www/domain.de/apps/mailman/index.php on line 5
[Thu Jan 31 00:15:59.902806 2019] [php7:notice] [pid 2206] [client 31.16.189.122:60868] PHP Notice:  Undefined index: path in /var/www/domain.de/apps/mailman/templates/login.php on line 15
[Thu Jan 31 00:18:06.883007 2019] [php7:notice] [pid 2211] [client 31.16.189.122:60876] PHP Notice:  Undefined index: path in /var/www/domain.de/apps/mailman/index.php on line 5
[Thu Jan 31 00:18:06.883972 2019] [php7:notice] [pid 2211] [client 31.16.189.122:60876] PHP Notice:  Undefined index: path in /var/www/domain.de/apps/mailman/templates/login.php on line 15
[Thu Jan 31 00:18:09.009590 2019] [php7:error] [pid 2216] [client 31.16.189.122:60877] PHP Fatal error:  Uncaught Error: Call to a member function bind_param() on boolean in /var/www/domain.de/apps/mailman/functions.php:112\nStack trace:\n#0 /var/www/domain.de/apps/mailman/functions.php(131): save_session(Array, 1)\n#1 /var/www/domain.de/apps/mailman/index.php(11): verify_logged_in(Array, 'login', 'pass')\n#2 {main}\n  thrown in /var/www/domain.de/apps/mailman/functions.php on line 112, referer: https://app.domain.de/
[Thu Jan 31 00:23:42.708957 2019] [php7:error] [pid 1391] [client 31.16.189.122:60925] PHP Fatal error:  Uncaught Error: Call to a member function bind_param() on boolean in /var/www/domain.de/apps/mailman/functions.php:112\nStack trace:\n#0 /var/www/domain.de/apps/mailman/functions.php(131): save_session(Array, 1)\n#1 /var/www/domain.de/apps/mailman/index.php(11): verify_logged_in(Array, 'login', 'pass')\n#2 {main}\n  thrown in /var/www/domain.de/apps/mailman/functions.php on line 112, referer: https://app.domain.de/index.php?path=home

ill get HTTP Error 500

**Comment by svenseeberg** [comment]
Sorry, I did not see this issue. Was the database configured correctly? Did you create the `logins` SQL table?

**Comment by axiades** [comment]
[Mon May 18 15:43:21.472545 2020] [proxy_fcgi:error] [pid 56442:tid 139947275753216] [client 217.228.117.99:65422] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function bind_param() on bool in /var/www/domain.tld/mailadminl/functions.php:176\nStack trace:\n#0 /var/www/tinytina.dev/mailadminl/functions.php(206): save_session(Array, 1)\n#1 /var/www/tinytina.dev/mailadminl/index.php(11): verify_logged_in(Array, 'admin@domain....', 'password')\n#2 {main}\n  thrown in /var/www/domain.tld/mailadminl/functions.php on line 176', referer: https://mailadminl.domain.tld:8443/

Webserver is a Apache2 Webserver with PHP7.3-FPM
logins SQL Table is created..


Please Help me ill get HTTP Error 500
